### ISSUE TITLE
Unitscan broke wand cast

### ISSUE THREAD

**Issue by bordarino** [GryllsAddons/unitscan-turtle#1]
When I try cast wand neare spot with rare its don't cast with "interrupted" message. I think it's because addon try target nearest mobs and its cancel wand cast. 
Any way to fix this?

**Comment by GryllsAddons** [comment]
Thank you for raising this. I'm unable to replicate it breaking the wand cast - it will show an "Interrupted" message when the mob dies (i'll look into this) but it doesn't appear to stop the wanding at least for me. Could you confirm it's stopping the actual wand casts? I've also amended the checking interval so please try using the new version.

**Comment by GryllsAddons** [comment]
I've uploaded a new version with changes to target switching, please let me know if this issue occurs in the new version.

**Comment by bordarino** [comment]
> I've uploaded a new version with changes to target switching, please let me know if this issue occurs in the new version.

Thanks for an answering and your work! 
I tested it's today and now it's work better. 
I tested neare farmer soliden in UD starting zone. I think that adding a delay for scanning work great now. Few times its broke my wand cast, but if i spam it its work. Maybe add a slash command to turn off scanning in combat will be good if it's possible?

**Comment by GryllsAddons** [comment]
Thank you i'm glad it's working better for you! I've tried to duplicate your issue - I've realised that the "Interrupted" message appears in the default UI without the addon when killing mobs when wanding. I've also tested with a different checking intervals (up to 10 times per second) with the mob alert going off constantly while wanding and haven't been able to replicate breaking wanding. Could you try disabling all other addons and see if the wanding still breaks? I'm wondering if it could be another addon causing the issue.

**Comment by bordarino** [comment]
I found that [notoggle](https://github.com/shirsig/notoggle) addon do it for me. Its work just fine separated but with unitscan its broke my wand cast. 
I'm so sorry for wasting your time. Thanks for your help!

**Comment by GryllsAddons** [comment]
Thank you! no worries, glad we figured it out! please let me know if you find any other issues :)
