### ISSUE TITLE
Snowball boss from Winter Veil event

### ISSUE THREAD

**Issue by EyeOfTheBeast** [GryllsAddons/unitscan-turtle#6]
The Snowball Winter Veil world boss (5-6hr respawn) could be a dangerous target if you are inside of the cave when he is pulled: https://database.turtle-wow.org/?npc=50112

He can do a cave-wide frostbolt volley and kill people. Thus you may want to add him to the list of unitscan mobs.

**Comment by GryllsAddons** [comment]
Added :)
